name: HexagonClearPlot
version: 1.0.0-BETA
main: net.elicodes.clearplot.Main
author: EliCodes
depend: [FastAsyncWorldEdit, PlotSquared]
load: POSTWORLD
commands:
  clearplot:
    aliases: [cp, limparterreno]