MySQL:
  ativar: false
  usuario: root
  senha: ''
  database: test
  host: localhost:3306

Region: #Base = Total de Blocos de um lado horizontal, Perimetro = Total de blocos de um lado vertical.
  #Area = Base x Perimetro.
  Base: 50
  Perimetro: 50

Blocks-BlackList: #Caso não queira blacklist de blocos. Deixe -> Blocks-BlackList: [].
  - CHEST
  - ENDER_CHEST

Formatter:
  - '' #Deixe vazio!
  - 'K'
  - 'M'
  - 'B'
  - 'T'
  - 'Q'
  - 'QQ'
  - 'S'
  - 'SS'
  - 'O'
  - 'N'
  - 'D'

CP-Item:
  skull-url: ''
  material: GOLD_SPADE
  data: 0
  name: '&aLimpador de terreno'
  lore:
    - ''
    - ' &7Limpe o seu terreno clicando direito em cima de sua plot.'
    - ' &c&lATENÇÃO: &7Ele limpará apenas da grama para baixo, caso queira'
    - ' &7limpar da grama pra cima, como &fconstruções&7, utilize o comando: &f/plot clear.'
    - ''
    - '  &eClique direito para limpar.'
  glow: false

CMD Permission: 'clearplot.admin'